- name: Install depends for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: yes

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
- name: Update and install docker
  ansible.builtin.apt:
    update_cache: yes
    name: docker-ce
    state: latest




- name: Create container
  docker_container:
    name: "Kibana"
    image: "kibana:8.6.2"
    ports:
    - "5601:5601"
    env:
        ELASTICSEARCH_HOSTS='["http://{{ hostvars['elasticsearch-host'].ansible_host }}:9200"]'
    state: started
    restart_policy: always

- name: docker container ls -la
  tags: container_ls
  shell: "docker container ls -la"
  register: container_info

- name: docker container ls -la result
  tags: container_ls
  debug:
    msg: "{{container_info.stdout_lines}}"
